### PR TITLE
telemetry: prefix keys for classification in vscode

### PR DESCRIPTION
**Pull request by connor4312**
Opted to remap it inside the telemetry reporter so that this is a single change and doesn't break the exposed interface.

Once this is published and packages updated, https://github.com/microsoft/vscode/issues/97628 can be closed.

### CODE REVIEW

**Comment by roblourens** [comment]
Where are the !-prefixed keys filtered out? Will this cause any issues for VS people looking at telemetry if they want to query for old non-prefixed events and also the new events? @digeff

**Comment by connor4312** [comment]
They're filtered in VS Code core, as of https://github.com/microsoft/vscode/pull/97627

An alternative approach would be to add some `_errorProperties` property to the log message, which would not require changing property names. I can make that change if we think that's better.

**Comment by roblourens** [comment]
I think this is probably find but let's clear it with @digeff

**Comment by digeff** [comment]
Assuming we get the telemetry properties in the backend, and nothing drops them because they start with !, then this is fine. Do you know if our backend supports an ! at the start of the properties?

**Comment by connor4312** [comment]
@digeff I'm not sure what backend you guys use on the VS side but I see these properties come through correctly to the VS Code Kusto

**Comment by digeff** [comment]
I think we use the same infrastructure, so I'd expect it to work in VS too.

Given that you already wrote this code, I'd merge it as is. I'll insert this into VS and see if I get the new properties. If I find any issues, we can implement the fix in a new PR. What do you think?

**Comment by connor4312** [comment]
Sounds good

**Pull request merged**
