### PR TITLE
Now we keep a collection to determine if a script needs to be added, removed or changed on the client

### PR DESCRIPTION
**Pull request by digeff**
Now we keep a collection to determine if a loaded script needs to be added, removed or changed on the client.

This fixes an issue on Edge where we are trying to remove scripts that are not there, and trying to add scripts that already are there.

### CODE REVIEW

**Comment by digeff** [comment]
@rakatyal Can you take a look please?

**Comment by roblourens** [comment]
> This fixes an issue on Edge where we are trying to remove scripts that are not there, and trying to add scripts that already are there.

Why does that happen?

**Comment by digeff** [comment]
We have a race condition between: onExecutionContextsCleared() and onScriptParsed(). When a script gets added to this._earlyScripts we can try to remove it before we add it.

In Edge this happens often at the moment because of a bug when we navigate to a new page we get a onScriptParsed() for the new page before onExecutionContextsCleared() is called.

I think this can probably also happen on Chrome, but I haven't seen it happen yet.

**Comment by auchenberg** [comment]
Question: If this only happens in Edge, why isn't this fixed in the platform?

**Comment by digeff** [comment]
Edge platform is fixing their bug too. I'm fixing this here because we want to get this working as soon as possible, and also because I think that this can potentially happen on Chrome too.

**Comment by roblourens** [comment]
I don't think this happens in Chrome, I think this is duplicating information that the browser should keep track of. I'm ok taking it as a workaround for the bug as long it we mark it as such. Will look at it on Monday.

**Pull request merged**
