### PR TITLE
Fix undefined/null error when property value not set

### PR DESCRIPTION
**Pull request by dlebu**
@roblourens @digeff

### CODE REVIEW

**Comment by roblourens** [comment]
What was the scenario that caused this error?

**Comment by dlebu** [comment]
@roblourens It was expanding the globals in VS while stopped at a breakpoint.

**Comment by roblourens** [comment]
Was this in master, or the VS branch? Do you have the full stack handy?

If the VS branch, I might have fixed the underlying issue awhile back, but I'll still take the PR.

**Comment by dlebu** [comment]
It was the latest shipped with VS, which I believe is the VS branch. Here is a full stack:

```
Error processing "variables": TypeError: Cannot read property 'length' of undefined
    at trimProperty (C:\ProgramData\Microsoft\VisualStudio\NodeAdapter\68d8e6f6\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:167:18)
    at propertyPreviewToString (C:\ProgramData\Microsoft\VisualStudio\NodeAdapter\68d8e6f6\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:161:19)
    at props.map.prop (C:\ProgramData\Microsoft\VisualStudio\NodeAdapter\68d8e6f6\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:151:43)
    at Array.map (native)
    at getObjectPreview (C:\ProgramData\Microsoft\VisualStudio\NodeAdapter\68d8e6f6\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:151:14)
    at Object.getRemoteObjectPreview (C:\ProgramData\Microsoft\VisualStudio\NodeAdapter\68d8e6f6\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:194:17)
    at NodeDebugAdapter.createObjectVariable (C:\ProgramData\Microsoft\VisualStudio\NodeAdapter\68d8e6f6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1383:33)
    at NodeDebugAdapter.remoteObjectToVariable (C:\ProgramData\Microsoft\VisualStudio\NodeAdapter\68d8e6f6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1325:33)
    at NodeDebugAdapter.internalPropertyDescriptorToVariable (C:\ProgramData\Microsoft\VisualStudio\NodeAdapter\68d8e6f6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1090:21)
 [...]
```

**Pull request merged**
