### PR TITLE
Check if 'Debugger.setAsyncCallStackDepth' method unimplemented

### PR DESCRIPTION
**Pull request by iTOYS**
Fix for #226

### CODE REVIEW

**Comment by roblourens** [comment]
This won't fix it, the problem is that the runtime doesn't implement it. You need to call the method and ignore the error if it returns failure.

**Comment by iTOYS** [comment]
I already fixed it in my code. Just ignore that error. But I thought it's correct to check if method implemented.

**Comment by roblourens** [comment]
That check doesn't tell you if it's implemented, that object is just a proxy calling the target with whatever you give it.

**Comment by iTOYS** [comment]
Oh, I see. It won't work(

**Pull request closed without merging**
