### PR TITLE
Added support for basic color escape sequencies on Debug Console

### PR DESCRIPTION
**Pull request by rdegelo**
Added support for bold font style on Debug Console.

Background color can be easily implemented using the same approach.
If this PR gets accepted, I can add background colors support.

### CODE REVIEW

**Comment by roblourens** [comment]
This looks great, but the font-weight doesn't appear to have any affect in the Debug Console. Is it working for you? I don't know whether vscode supports it.

**Comment by rdegelo** [comment]
It works for me: 
```
console.log('%c Normal font weight ', 'color: blue');
console.log('%c Normal font weight ', 'color: blue; font-weight: bold');
```

Result: 
image

To check what is supported, you can see this file: 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugANSIHandling.ts#L70

**Comment by roblourens** [comment]
I see it, the problem is that the debug console uses the Monaco font on macos, which doesn't support a bold font weight.

**Comment by rdegelo** [comment]
Cool, 
When I have time I'll add background/underline support and post a new PR.

**Pull request merged**
