### PR TITLE
Add emulation commands to chrome connection

### PR DESCRIPTION
**Pull request by PatoBeltran**
Add emulation chrome commands which are helpful for viewport resizing.

### CODE REVIEW

**Comment by auchenberg** [comment]
The purpose of the core debugger is not to provide a client library for the APIs supported for by Chrome and other Chrome Debugger Protocol compliant runtimes.

If this is needed I suggest that we could add a generic method to trigger commands on the connected CDP connection, @roblourens?

**Comment by nojvek** [comment]
Who will be calling the functions? Aren't they going to be dead functions for time being?

**Comment by roblourens** [comment]
I told Patricio to add these, to hold vscode-cordova over until we do something like #46

**Comment by auchenberg** [comment]
I see this as a slippery slope. These should be added in the runtime specific debugger, and not in the core. The core should expose generic logic to make API requests.

**Comment by roblourens** [comment]
`ChromeConnection` is sort of the generic logic to make API requests. It will be outsourced to some external module, which will be pretty easy because it's already totally separate from the actual logic in -core.

**Comment by auchenberg** [comment]
And yet you just expanded the API surface exposed by `core` to include API Emulation features that will you will need to support in the future to be backwards compatible? 

I made my point, but you are the maintainer, so it's your call.

**Comment by roblourens** [comment]
Well, I'm not concerned about backwards compatibility here, to be honest. This interface will break when we do #46 and replace ChromeConnection with some other library that provides the CDP endpoint. And that interface should break whenever the protocol changes.

**Comment by nojvek** [comment]
That's right, the goal of crdi is to pull nightly changes from chromium
protocol jsons, generate an interface like this and publish to npm if any
changes.

Since it has both the adapter and client interfaces, the edge adapter can
implement the adapter interface and vscode / other clients can use the
client interface.

The request, response, event object interfaces are shared between client
and server.

e.g.

https://github.com/nojvek/chrome-remote-debug-interface/blob/master/src/crdi.ts

**Comment by auchenberg** [comment]
Let me keep you in mind that the supported API is an dynamic target and depend on the target client, hence the added ability to fetch `protocol.json` on demand on other clients and in runtimes like Edge and Node. 

Relaying on the Chromium specific API would be a short term thing.

**Pull request merged**
